#!/usr/bash
echo "Running apt-get update"
#sudo apt-get update

echo "Installing Operating System dependencies"
#sudo apt-get -y install git gcc libffi-dev libssl-dev python-dev python-cryptography wiringpi

echo "Installing Python dependencies"
#sudo pip install Flask Flask-SSLify flask_sqlalchemy ipaddress netifaces netaddr psutil simplepam wiringpi

if [ -z "$PiControlDirectory" ]
then
	PiControlDirectory="/usr/local/src"
fi

cd $PiControlDirectory

echo "Cloning PiControl from GitHub to ${PiControlDirectory}"
sudo git clone https://github.com/bcarroll/PiControl.git

sudo chmod +x PiControl/PiControl.sh
sudo chown -R $USER PiControl